app/mod_reader/controllers.py
# -*- coding: UTF-8 -*-
from flask import Blueprint, Markup, request, render_template, flash, g, session, redirect, url_for, jsonify
from flask_login import LoginManager, login_user, logout_user, current_user, login_required
from collections import OrderedDict

from app import logger
from app.mod_reader.models import RSSData, FlightData
from app.mod_reader.forms import DataSearcher
from app.mod_reader.helper import rss_parser, dbhelper, flightparser

mod_reader = Blueprint('rss', __name__, url_prefix='')


@mod_reader.route('/data-viewer', methods=['GET', 'POST'])
def data_viewer():
    r = dbhelper.remove_priceline_deals(FlightData.objects(status=True))
    expired_deals = dbhelper.remove_priceline_deals(FlightData.objects(status=False).order_by('-created'))[:3]
    data = None
    if len(r) > 0:
        data = r
    else:
        flash(u"no data available yet!", "danger")

    return render_template("user/data_viewer.html",
                           data=data,
                           expired_deals=expired_deals,
                           data_holder=OrderedDict([("RECENT FLIGHT DEALS", data), ("OLDER DEALS", expired_deals)])
                           )


@mod_reader.route('/data-searcher', methods=['GET', 'POST'])
def data_searcher():
    form = DataSearcher(request.form)
    data = {}
    if request.method == "POST" and form.validate_on_submit():
        _attributes = ["search_arrival", "search_departure", "search_airlines", "search_title", "search_price", "search_dates"]
        for a in _attributes:
            # eg: dbhelper.search_arrival(form.search_arrival.data)
            if getattr(getattr(form, a), "data"):
                data[a] = getattr(dbhelper, a)(getattr(getattr(form, a), "data"))

        data["search_all"] = dbhelper.search_all(arrival=form.search_arrival.data,
                                                 departure=form.search_departure.data,
                                                 airlines=form.search_airlines.data,
                                                 title=form.search_title.data,
                                                 dates=form.search_dates.data)

        data["search_arrival_departure"] = dbhelper.search_arrival_departure(arrival=form.search_arrival.data,
                                                                             departure=form.search_departure.data)
    return render_template("user/data_searcher.html", form=form, data=data)

app/templates/user/data.html
{% extends "base.html" %}
{% block meta_description %}Spotlight Flights{% endblock %}
{% block title %}Feed Scraper{% endblock %}
{% block body %}

    {% include "navbar.html" %}
    <div class="container">
        <h1>Data Parser</h1>
        <div class="alert alert-warning" role="alert">
            <p>clicking on the button will scrape the feed from: <b>"http://www.secretflying.com/feed/"</b></p>
        </div>

        <button class="btn btn-lg btn-warning" id="execute_rss_feed_ajax">Execute RSS!</button>
    </div>

{% endblock %}

{% block javascripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='js/reader/execute-rss.js') }}"></script>
{% endblock %}

app/templates/user/data_searcher.html
{% extends "base.html" %}
{% block meta_description %}Spotlight Flight{% endblock %}
{% block title %}Search Flight Deals{% endblock %}
{% block body %}

    {% include "navbar.html" %}
    <div class="container">
        <h1>Search Flight Deals</h1>
        <form action="{{ url_for('rss.data_searcher') }}" method=post>
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.search_arrival.label }} {{ form.search_arrival(class_="form-control input-lg") }}
                {{ form.search_departure.label }} {{ form.search_departure(class_="form-control input-lg") }}
                {{ form.search_title.label }} {{ form.search_title(class_="form-control input-lg") }}
                {{ form.search_airlines.label }} {{ form.search_airlines(class_="form-control input-lg") }}
                {{ form.search_dates.label }} {{ form.search_dates(class_="form-control input-lg") }}
                <!--{{ form.search_price.label }} {{ form.search_price(class_="form-control input-lg") }}-->
            </div>
            <button type="submit" class="btn btn-default btn-lg">Submit</button>
        </form>

        {% if data %}
            {% for k, v in data.iteritems() %}
                {% if v %}
                    <div class="alert alert-success" role="alert">
                        <h2>{{ k }}</h2>
                        {% for d in v %}
                            {% for _a in d %}
                                <p><b>{{ _a }}:</b> {{ d[_a] }}</p>
                            {% endfor %}
                            <hr>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="alert alert-warning" role="alert">No results for <b>{{ k }}</b></div>
                {% endif %}
                <hr>
            {% endfor %}
        {% endif %}

    </div>
{% endblock %}

app/templates/user/data_viewer.html
{% extends "base.html" %}
{% block meta_description %}Spotlight Flight helps you find and create alerts on the cheapest flight deals{% endblock %}
{% block title %}View Flight Deals{% endblock %}
{% block body %}

    {% include "navbar.html" %}
    <div class="container">
        {% for k, data in data_holder.iteritems() %}
            {% if data %}
                <h1 class="text-center header_text">{{ k }}</h1>
                {% for i in data %}
                    {% if loop.index == 1 %}<div class="row">{% endif %}
                        {% if i["deal_url"] and "http://www.dpbolvw.net" not in i["deal_url"] %}
                            {% set tile_class = "yellow" %}
                            {% set btn_name = "SEE DEAL" %}
                        {% else %}
                            {% set tile_class = "blue" %}
                            {% set btn_name = "PRICELINE" %}
                        {% endif %}
                        <div class="flight_deals col-lg-4">
                            <!--START OF FLIGHT DEALS DISPLAY-->
                            {% include "auth/flight_deals_display.html" %}
                            <!--END OF FLIGHT DEALS DISPLAY-->
                            {% if current_user.is_authenticated %}
                                <a class="btn btn-{{tile_class}} btn-theme btn-lg" href='{{ i["deal_url"] }}' role="button" style="font-weight: 600; letter-spacing: 3px;" target="_blank" rel="nofollow">{{btn_name}}</a>
                            {% else %}
                                <a class="btn btn-blue btn-theme btn-lg" href='/login' role="button" style="font-weight: 600; letter-spacing: 3px;">
                                    <i class="fa fa-lock" aria-hidden="true"></i> LOG IN TO VIEW
                                </a>
                            {% endif %}
                        </div>
                    {% if loop.index %3 == 0 %}</div><hr><div class="row">{% endif %}
                    {% if loop.last %}</div>{% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    </div>

{% endblock %}